name: Pull Request Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install packages
        run: npm install
      
      - name: Compile TypeScript
        run: |
          npm run build:tsc

      - name: Run tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint